    # run

    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes
      tags:
      - core
      - provision

    - name: uri ansible module requirements
      apt: pkg={{ item }}
      sudo: yes
      with_items:
      - libpython2.7-stdlib
      - python-httplib2
      tags:
      - core
      - provision

    - name: Install curl
      apt: pkg=curl
      sudo: yes
      tags:
      - core
      - provision

    - name: Install Timezone data
      apt: pkg=tzdata
      sudo: yes
      tags:
      - core
      - run

    - name: Set timezone
      copy: content=Australia/Melbourne dest=/etc/timezone
      sudo: yes
      tags:
      - core
      - run

    - name: Set Local Time
      shell: dpkg-reconfigure --frontend noninteractive tzdata
      sudo: yes
      tags:
      - core
      - run

    - name: Install NTP
      apt: pkg={{ item }}
      with_items:
        - ntp
        - ntpdate
      sudo: yes
      tags:
      - core
      - run

    # development

    - name: Install avahi
      apt: pkg=avahi-daemon
      sudo: yes
      tags:
      - core
      - development

    - name: Install vim
      apt: pkg=vim
      sudo: yes
      tags:
      - core
      - development

    - name: Update .vimrc
      lineinfile: dest=~/.vimrc line="{{ item }}" create=yes
      with_items:
      - :set tabstop=4
      - :set shiftwidth=4
      - :set expandtab
      tags:
      - core
      - development
