    - name: Add java 8 ppa
      apt_repository: repo="ppa:openjdk-r/ppa" update_cache=yes
      tags:
      - clojure
      - development
      sudo: yes

    - name: Install java
      apt: pkg=openjdk-8-jre
      tags:
      - clojure
      - development
      sudo: yes

    - name: Install lein
      get_url: url=https://raw.github.com/technomancy/leiningen/stable/bin/lein dest=/usr/local/bin/lein mode=0755
      tags:
      - clojure
      - development
      sudo: yes

    - name: Install git
      apt: pkg=git-core
      tags:
      - clojure
      - development
      sudo: yes

    - name: Install vim
      apt: pkg=vim
      tags:
      - clojure
      - development
      sudo: yes

    - name: Install VimClojure
      git: repo=https://github.com/vim-scripts/VimClojure.git dest=~/.vim/bundle/VimClojure
      tags:
      - clojure
      - development

    - name: Update .vimrc
      lineinfile: dest=~/.vimrc line="{{ item }}" create=yes
      with_items:
      - syntax on
      - filetype plugin indent on
      tags:
      - clojure
      - development

